### ISSUE TITLE
Code version is not avaliable

### ISSUE THREAD

**Issue by devopsdymyr** [PacktPublishing/Hands-On-Auto-DevOps-with-GitLab-CI#1]
AS per the video all code version is not available in the git hub.
Can you please update all version of the code

**Comment by AlanHohn** [comment]
Can you provide the specifics of the video you are viewing? I can help you find the associated code 
files or provide additional information. Thanks.

**Comment by devopsdymyr** [comment]
as per the video all version of gitlab-ci.yml file is not there,Available file in github is final code.
Tried to deploy dynamic environment in kubernetes which is getting failed tin test stage. 
Dynamic Environments and Review Apps-->/kube-deploy/.gitlab-ci.yml

There is one more issue while connecting next repository with kubernetes integration.
i have integrated with following documents link https://docs.gitlab.com/ee/user/project/clusters/#add-existing-kubernetes-cluster

After integrating with existing kube cluster deploy stage will get failed due to there is no authentication or kubeconfig details in the deploy stage

**Comment by devopsdymyr** [comment]
@AlanHohn  thanks for your response

**Comment by AlanHohn** [comment]
I have updated the `README.md` file in the `kube-deploy` folder to better provide instructions for getting the test stage running. Apologies for the confusion there. For the deploy stage, GitLab should set Kubernetes environment variables automatically when a cluster is configured, as long as the `environment` is set for a job. To troubleshoot, there are a couple things you can try:

1. Add `echo` statements in the `deploy` job for some of the [Kubernetes variables provided by GitLab](https://docs.gitlab.com/ee/user/project/clusters/#deployment-variables).
2. Make sure you can use the same CA certificate and service token from the command line using `kubectl`.
3. Check the reachability of the API server from within your GitLab build using `wget -O - <api server URL>` as part of the `deploy` job.
4. Check the ability to authenticate with the API server by adding `kubectl version` and `kubectl can-i get po` in the `deploy` job.
